/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      Konstrukt24.hpp                            ||
||     Author:    Autogenerated                              ||
||     Generated: 12.01.2022                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _Konstrukt24_hpp_
#define _Konstrukt24_hpp_


#include "Delegat24.hpp"
#include "Control24.hpp"
#include "Instanz24.hpp"


#endif
