/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      namespacer.h                               ||
||     Author:    Kalle                                      ||
||     Generated: 08.10.2017                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/


#ifndef STEPFLOW
#define STEPFLOW(subspace,DECL) STEPFLOW_ ## subspace ::DECL
#endif

#ifndef BEGIN_STEPFLOW
#define BEGIN_STEPFLOW(space) BEGIN_STEPFLOW_ ## space
#endif
#ifndef ENDOF_STEPFLOW
#define ENDOF_STEPFLOW(space) ENDOF_STEPFLOW_ ## space
#endif
#ifndef USING_STEPFLOW
#define USING_STEPFLOW(space) USING_STEPFLOW_ ## space
#endif

#ifdef BEGIN_STEPFLOW_NAMESPACE
#undef BEGIN_STEPFLOW_NAMESPACE
#endif
#ifdef ENDOF_STEPFLOW_NAMESPACE
#undef ENDOF_STEPFLOW_NAMESPACE
#endif
#ifdef USING_STEPFLOW_NAMESPACE
#undef USING_STEPFLOW_NAMESPACE
#endif

#if !defined(SET_STEPFLOW_NAMESPACE)
     #define SET_STEPFLOW_NAMESPACE stepflow
#endif

#if !(SET_STEPFLOW_NAMESPACE == -1 || SET_STEPFLOW_NAMESPACE == EMPTY)
#define STEPFLOW_NAMESPACE SET_STEPFLOW_NAMESPACE
#endif

#ifdef INCLUDE_CONTROLLED_VALUES
#if !defined(SET_CONTROLLERSPACE)
#define SET_CONTROLLERSPACE values
#endif
#if !(SET_CONTROLLERSPACE == -1 || SET_CONTROLLERSPACE == EMPTY)
#define CONTROLLERS_NAMESPACE SET_CONTROLLERSPACE
#ifdef STEPFLOW_NAMESPACE
namespace STEPFLOW_NAMESPACE {
 namespace CONTROLLERS_NAMESPACE {
 }
}
#define BEGIN_STEPFLOW_VALUES namespace STEPFLOW_NAMESPACE{ namespace CONTROLLERS_NAMESPACE{
#define ENDOF_STEPFLOW_VALUES }}
#define STEPFLOW_VALUES STEPFLOW_NAMESPACE::CONTROLLERS_NAMESPACE
#define USING_STEPFLOW_VALUES using namespace STEPFLOW_VALUES;
#else
#define BEGIN_STEPFLOW_VALUES namespace CONTROLLERS_NAMESPACE{
#define ENDOF_STEPFLOW_VALUES }
#define STEPFLOW_VALUES CONTROLLERS_NAMESPACE
#define USING_STEPFLOW_VALUES using namespace CONTROLLERS_NAMESPACE;
#endif
#else
#if defined(STEPFLOW_NAMESPACE)
#define CONTROLLERS_NAMESPACE STEPFLOW_NAMESPACE
#define BEGIN_STEPFLOW_VALUES namespace STEPFLOW_NAMESPACE{
#define ENDOF_STEPFLOW_VALUES }
#define STEPFLOW_VALUES STEPFLOW_NAMESPACE
#define USING_STEPFLOW_VALUES using namespace STEPFLOW_NAMESPACE;
#else
#define CONTROLLERS_NAMESPACE
#define BEGIN_STEPFLOW_VALUES
#define ENDOF_STEPFLOW_VALUES
#define USING_STEPFLOW_VALUES
#endif
#endif
#define BEGIN_STEPFLOW_NAMESPACE BEGIN_STEPFLOW_VALUES
#define ENDOF_STEPFLOW_NAMESPACE ENDOF_STEPFLOW_VALUES
#define USING_STEPFLOW_NAMESPACE USING_STEPFLOW_VALUES
#undef INCLUDE_CONTROLLED_VALUES
#endif

#ifdef INCLUDE_STEP_LISTS
#if !defined(SET_LISTS_NAMESPACE)
#define SET_LISTS_NAMESPACE lists
#endif
#if !(SET_LISTS_NAMESPACE == -1 || SET_LISTS_NAMESPACE == EMPTY)
#define STEPLISTS_NAMESPACE SET_LISTS_NAMESPACE
#ifdef STEPFLOW_NAMESPACE
namespace STEPFLOW_NAMESPACE {
 namespace STEPLISTS_NAMESPACE {
 }
}
#define BEGIN_STEPFLOW_LISTS namespace STEPFLOW_NAMESPACE{ namespace STEPLISTS_NAMESPACE{
#define ENDOF_STEPFLOW_LISTS }}
#define STEPFLOW_LISTS STEPFLOW_NAMESPACE::STEPLISTS_NAMESPACE
#define USING_STEPFLOW_LISTS using namespace STEPFLOW_LISTS;
#else
#define BEGIN_STEPFLOW_LISTS namespace STEPLISTS_NAMESPACE{
#define ENDOF_STEPFLOW_LISTS }
#define STEPFLOW_LISTS STEPLISTS_NAMESPACE
#define USING_STEPFLOW_LISTS using namespace STEPLISTS_NAMESPACE;
#endif
#else
#if defined(STEPFLOW_NAMESPACE)
#define STEPLISTS_NAMESPACE STEPFLOW_NAMESPACE
#define BEGIN_STEPFLOW_LISTS namespace STEPFLOW_NAMESPACE{
#define ENDOF_STEPFLOW_LISTS }
#define STEPFLOW_LISTS STEPFLOW_NAMESPACE
#define USING_STEPFLOW_LISTS using namespace STEPFLOW_NAMESPACE;
#else
#define STEPLISTS_NAMESPACE
#define BEGIN_STEPFLOW_LISTS
#define ENDOF_STEPFLOW_LISTS
#define USING_STEPFLOW_LISTS
#endif
#endif
#define BEGIN_STEPFLOW_NAMESPACE BEGIN_STEPFLOW_LISTS
#define ENDOF_STEPFLOW_NAMESPACE ENDOF_STEPFLOW_LISTS
#define USING_STEPFLOW_NAMESPACE USING_STEPFLOW_LISTS
#undef INCLUDE_STEP_LISTS
#endif


